### PR TITLE
Bump version to 2.4.1

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>

### Description
Bump version to 2.4.1

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by amsiglan** [comment]
@AWSHurneyt Do we also need to update the workflow files?

**Comment by AWSHurneyt** [comment]
@gaiksaya Could you update the version references for the [cypress](https://github.com/opensearch-project/security-analytics-dashboards-plugin/blob/main/.github/workflows/cypress-workflow.yml#L10), and [unit](https://github.com/opensearch-project/security-analytics-dashboards-plugin/blob/main/.github/workflows/unit-tests-workflow.yml#L10) test workflow as well?

**Comment by amsiglan** [comment]
@gaiksaya Should we create PR against main first and back port that to 2.x and 2.4?

**Comment by gaiksaya** [comment]
> @gaiksaya, @AWSHurneyt Should we create PR against main first and back port that to 2.x and 2.4?

Main should be pointing at 3.x. Version increments, should be at respective branch.

**Comment by gaiksaya** [comment]
Also @AWSHurneyt the unit test workflow does not contain any `2.4.0` versions in 2.4 branch https://github.com/opensearch-project/security-analytics-dashboards-plugin/blob/2.4/.github/workflows/unit-tests-workflow.yml
Just FYI so no changes there. Lmk if I am missing anything

**Comment by AWSHurneyt** [comment]
@gaiksaya 
> Also @AWSHurneyt the unit test workflow does not contain any `2.4.0` versions in 2.4 branch https://github.com/opensearch-project/security-analytics-dashboards-plugin/blob/2.4/.github/workflows/unit-tests-workflow.yml Just FYI so no changes there. Lmk if I am missing anything

Yeah no problem. I was looking at the `main` branch when I directed to that workflow, which references a specific tag as opposed to a specific branch. Thanks for clarifying.

**Comment by gaiksaya** [comment]
Looks like the CI is failing. @AWSHurneyt @amsiglan Can you take a look at it?
Thanks!

**Comment by AWSHurneyt** [comment]
> Looks like the CI is failing. @AWSHurneyt @amsiglan Can you take a look at it? Thanks!

The backend plugin hasn't been bumped yet https://github.com/opensearch-project/security-analytics/pull/160. The backend depends on the alerting plugin https://github.com/opensearch-project/alerting/pull/683, which also hasn't been bumped yet because it depends on notifications https://github.com/opensearch-project/notifications/pull/570.

**Review by rishabh6788 — APPROVED** [review]

**Review by AWSHurneyt — APPROVED** [review]

**Pull request merged**
